// LOCALHOST ### 
GET http://localhost:8080/clients/

### create post###
POST http://localhost:8080/clients HTTP/1.1 content-type: application/json

    {
        "clientName": "Lois Lane",
        "contactInfo": "loislane@gmail.com",
        "registeredAt": "02/01/2023",
        "lastContacted": "04/01/2023",
        "accountManager": "Maria Chavez",
        "location": "342, 140, 135"
    }

### PUT contact###
 PUT http://localhost:8080/clients/6493c1263cb95133c763ec6e HTTP/1.1 content-type: application/json

    {
        "clientName": "Lee Wong",
        "contactInfo": "leewong@gmail.com",
        "registeredAt": "02/01/2023",
        "lastContacted": "04/01/2023",
        "accountManager": "Jhon Smith",
        "location": "340, 120, 115"
    }

### DELETE contact###
 DELETE http://localhost:8080/clients/6493c1263cb95133c763ec6e HTTP/1.1


### DEV PRODUCTION###

### GET default###
GET https://cse341-node-6oti.onrender.com/ 

### GET API swagger docs###
GET https://cse341-node-6oti.onrender.com/api-docs 
### GET all contacts###
GET https://cse341-node-6oti.onrender.com/clients 
### GET 1 contact###
GET https://cse341-node-6oti.onrender.com/clients/6493c1263cb95133c763ec6f
### POST - create contact###
POST http://cse341-node-6oti.onrender.com/clients HTTP/1.1 content-type: application/json

    {
        "clientName": "Lee Wong",
        "contactInfo": "leewong@gmail.com",
        "registeredAt": "02/01/2023",
        "lastContacted": "04/01/2023",
        "accountManager": "Jhon Smith",
        "location": "340, 120, 115"
    }
### PUT - update contact###
PUT http://cse341-node-6oti.onrender.com/clients/6493c1263cb95133c763ec70 HTTP/1.1 content-type: application/json

    {
        "clientName": "Mickey Mae",
        "contactInfo": "mickeymae@gmail.com",
        "registeredAt": "02/01/2023",
        "lastContacted": "04/01/2023",
        "accountManager": "Jhon Smith",
        "location": "343, 122, 113"
    }
### DELETE contact###
DELETE http://cse341-node-6oti.onrender.com/clients/6493c4ac3cb95133c763ec74 HTTP/1.1